### PR TITLE
Partial detection bypass

### PR DESCRIPTION
**Pull request by MrSleekZ**
Partially bypassed detection by removing patches, FPS counter and Background colour are the only features that currently work I think. I  will try and do a total bypass by re-writing the patches.

### CODE REVIEW

**Comment by Lemons1337** [comment]
Lol he doesn’t even know what that means. Every cheat that has ever been on this repository was skidded from other developers. He just steals code, gives himself credit, then goes on to the next cheat

**Comment by Lemons1337** [comment]
Also you can’t just rewrite the patches.... That won’t work

**Comment by MrSleekZ** [comment]
Re-write code/ patches

**Comment by MrSleekZ** [comment]
Plus I barely used JavaScript anyway, I use C++.

**Comment by THEGUY3ds** [comment]
Lol

**Pull request closed without merging**
